version: '3'

services:

  mysql_utn:
    image: mysql
    container_name: mysql_utn
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: utn
    volumes:
      - ./mysql/data/course:/var/lib/mysql
      - ./mysql/init/mysql_course-init.sql:/docker-entrypoint-initdb.d/mysql_course-init.sql:ro

      
  phpmyadmin_utn:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_utn
    restart: always
    ports:
      - 3000:80
    environment:
      PMA_HOST: mysql_utn
      PMA_PORT: 3306
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: mysql.utn.jhoacar.me
      LETSENCRYPT_HOST: mysql.utn.jhoacar.me
      LETSENCRYPT_EMAIL: jhoacar.utn@gmail.com
    depends_on:
      - mysql_utn

  mongo_utn:
    image: mongo:4.4-focal
    container_name: mongo_utn
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo/data/course:/data/db
      - ./mongo/init/mongo_course-init.js:/docker-entrypoint-initdb.d/mongo_course-init.js:ro

  mongo_express_utn:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo_express_utn
    restart: always
    ports:
      - 3001:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo_utn:27017/
      VIRTUAL_PORT: 8081
      VIRTUAL_HOST: mongo.utn.jhoacar.me
      LETSENCRYPT_HOST: mongo.utn.jhoacar.me
      LETSENCRYPT_EMAIL: jhoacar.utn@gmail.com
    depends_on:
      - mongo_utn
