// Generated by https://quicktype.io

export interface PokemonResponse2 {
    value:    Value;
    children: string;
}

export interface Value {
    token:    string;
    user:     string;
    pokemons: Pokemon[];
}

export interface Pokemon {
    data:       DataClass | string;
    status:     number;
    statusText: string;
    headers:    Headers;
    request:    Request;
}


export interface DataClass {
    abilities:                string[];
    base_experience:          number;
    forms:                    string[];
    height:                   number;
    held_items:               any[];
    id:                       number;
    is_default:               boolean;
    location_area_encounters: string;
    moves:                    string[];
    name:                     string;
    order:                    number;
    past_types:               any[];
    species:                  Species;
    sprites:                  Sprites;
    stats:                    string[];
    types:                    string[];
    weight:                   number;
}

export interface Species {
    name: string;
    url:  string;
}

export interface Sprites {
    back_default:       string;
    back_female:        null;
    back_shiny:         string;
    back_shiny_female:  null;
    front_default:      string;
    front_female:       null;
    front_shiny:        string;
    front_shiny_female: null;
    other:              string;
    versions:           string;
}
